export enum TimelineAction {
  VOTE_CAST = 'vote_cast', // Voto emitido
  VOTE_REVOKED = 'vote_revoked', // Voto revocado
  ELECTION_STARTED = 'election_started', // Elección iniciada
  ELECTION_ENDED = 'election_ended', // Elección finalizada
  VOTER_REGISTERED = 'voter_registered', // Votante registrado
  VOTER_UNREGISTERED = 'voter_unregistered', // Votante
  VOTER_UPDATED = 'voter_updated', // Votante actualizado
  OPTION_ADDED = 'option_added', // Opción añadida
  OPTION_REMOVED = 'option_removed', // Opción eliminada
  OPTION_UPDATED = 'option_updated', // Opción actualizada
  ELECTION_CREATED = 'election_created', // Elección creada
  ELECTION_DELETED = 'election_deleted', // Elección eliminada
  ELECTION_UPDATED = 'election_updated', // Elección actualizada
  VOTE_COUNTED = 'vote_counted', // Voto contado
  VOTE_UNCOUNTED = 'vote_uncounted', // Voto no contado
  VOTER_LOGGED_IN = 'voter_logged_in', // Votante
  VOTER_LOGGED_OUT = 'voter_logged_out', // Votante desconectado
  VOTER_PROFILE_VIEWED = 'voter_profile_viewed', // Perfil del
  voter_profile_viewed = 'voter_profile_viewed', // Perfil del votante visto
  VOTER_PROFILE_UPDATED = 'voter_profile_updated', // Perfil del votante
  VOTER_PASSWORD_CHANGED = 'voter_password_changed', // Contraseña del votante cambiada
  VOTER_EMAIL_VERIFIED = 'voter_email_verified', // Email del votante verificado
  VOTER_EMAIL_UPDATED = 'voter_email_updated', // Email del votante actualizado
  VOTER_CODE_GENERATED = 'voter_code_generated', // Código del votante generado
  VOTER_CODE_UPDATED = 'voter_code_updated', // Código del votante   actualizado
  VOTER_CODE_DELETED = 'voter_code_deleted', // Código del votante eliminado
  VOTER_CODE_USED = 'voter_code_used', // Código del votante utilizado
  VOTER_CODE_EXPIRED = 'voter_code_expired', // Código del votante expirado
  VOTER_CODE_INVALIDATED = 'voter_code_invalidated', // Código del votante invalidado
  VOTER_CODE_REGENERATED = 'voter code_regenerated', // Código del votante regenerado
  VOTER_CODE_RESET = 'voter_code_reset', // Código del votante   reseteado
  VOTER_CODE_VERIFIED = 'voter_code_verified', // Código del vot ante verificado
  VOTER_CODE_UNVERIFIED = 'voter_code_unverified', // Código del votante no verificado
  VOTER_CODE_USED_ONCE = 'voter_code_used_once', // Código del votante utilizado una vez
  VOTER_CODE_USED_MULTIPLE = 'voter_code_used_multiple', // Código   del votante utilizado múltiples veces
  VOTER_CODE_USED_IN_SESSION = 'voter_code_used_in_session', // Código del votante utilizado en sesión
  VOTER_CODE_USED_OUTSIDE_SESSION = 'voter_code_used_outside_session', // Código del votante utilizado fuera de sesión
  VOTER_CODE_USED_IN_ELECTION = 'voter_code_used_in_election', // Código del votante utilizado en elección
  VOTER_CODE_USED_IN_VOTE = 'voter_code_used_in_vote', // Código del votante utilizado en voto
  VOTER_CODE_USED_IN_OPTION = 'voter_code_used_in_option', // Código del votante utilizado en opción
}
